name: Deployment
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: cd documentation && yarn install
      - name: Deploy to GitHub pages
        env:
          GH_NAME: "ahtcx"
          GH_EMAIL: "alexandre@hitchcox.me"
        run: |
          cd documentation
          export GIT_USER="$GH_NAME"
          git config --global user.name "${GH_NAME}"
          git config --global user.email "${GH_EMAIL}"
          echo "machine github.com login ${GH_NAME} password ${{ secrets.GITHUB_TOKEN }}" > ~/.netrc
          yarn deploy
